<?php
/** @package Imoveis::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("ImovelMap.php");

/**
 * ImovelDAO provides object-oriented access to the imovel table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Imoveis::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class ImovelDAO extends Phreezable
{
	/** @var int */
	public $Id;

	/** @var string */
	public $Titulo;

	/** @var string */
	public $Descricao;

	/** @var date */
	public $DataDisponibilidade;

	/** @var longtext */
	public $Imagem;

	/** @var float */
	public $Valor;

	/** @var string */
	public $EmailContato;

	/** @var int */
	public $TelefoneContato;

	/** @var int */
	public $TipoImovelId;


	/**
	 * Returns the foreign object based on the value of TipoImovelId
	 * @return TipoImovel
	 */
	public function GetTipoImovel()
	{
		return $this->_phreezer->GetManyToOne($this, "fk_imovel_tipo_imovel1");
	}


}
?>