<?php
/** @package Imoveis::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("TipoImovelMap.php");

/**
 * TipoImovelDAO provides object-oriented access to the tipo_imovel table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Imoveis::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class TipoImovelDAO extends Phreezable
{
	/** @var int */
	public $Id;

	/** @var string */
	public $Descricao;


	/**
	 * Returns a dataset of Imovel objects with matching TipoImovelId
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetImovels($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "fk_imovel_tipo_imovel1", $criteria);
	}


}
?>